title: "Open Source Everything"
description: "A project by MyFirstBitcoin"
# The baseurl should match your repository name for project sites.
baseurl: "/Open-Source-Everything"
url: "https://myfirstbitcoin.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"  # Use the latest stable version if available

# Optional: plugins GitHub Pages supports
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation configuration for Minimal Mistakes
header:
  nav:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Projects"
      url: "/projects/"
    - title: "Contact"
      url: "/contact/"
